# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SocialMediaLogin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SocialMediaLogin
  # Pods for Facebook Login
  pod 'FBSDKLoginKit'
  
  #Pods for Google Login
  pod 'GoogleSignIn', '~> 5.0'
  
  #Pods for Twitter Login
  pod 'TwitterKit'

end
